site_name: Intel® Retail Organization
site_url: "https://intel-retail.github.io/documentation/"
repo_name: "intel-retail/documentation"
repo_url: "https://github.com/intel-retail/documentation"
docs_dir: ./docs_src
site_dir: ./docs
copyright: 'Copyright &copy; 2024 Intel Corporation'
use_directory_urls: false
theme:
  name: 'material'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo-white-75px.png'
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.tracking
    - search.suggest
    - search.highlight
    - navigation.top
    - toc.follow
    - toc.integrate
plugins:
  - search
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [../benchmark-scripts]
nav:
  - Home: 'index.md'
  - Architecture Decisions:
      - Pipelines: 'Architecture/pipelines.md'
      - v2.0.0:
          - Distributed Architecture: 'Architecture/v2.0.0/distributed-architecture.md'
          - Multiple OVMS JSON Config: 'Architecture/v2.0.0/multiple-ovms-json-config.md'
          - Performance Benchmarking: 'Architecture/v2.0.0/performance_benchmarking.md'
          - Profile Launcher: 'Architecture/v2.0.0/profile-launcher.md'
          - Target Device: 'Architecture/v2.0.0/target-device.md'
      - v3.0.0:
          - AiCSD Integration: 'Architecture/v3.0.0/aicsd-integration.md'
  - Performance Tools:
      - Benchmarking: 'performance-tools/benchmark.md'
      - Benchmarking APIs: 'performance-tools/api-docs.md'
  - Use Cases:
      - Automated Self Checkout:
          - Overview: 'use-cases/automated-self-checkout/automated-self-checkout.md'
          - Getting Started: 'use-cases/automated-self-checkout/getting_started.md'
          - Advanced Settings: 'use-cases/automated-self-checkout/advanced.md'
          - Performance: 'use-cases/automated-self-checkout/performance.md'
  - Releases: 'releasenotes.md'
extra_css:
  - ./stylesheets/index.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - ./stylesheets/branding.css
  - ./stylesheets/extra.css
extra_javascript:
  - 'https://unpkg.com/lunr/lunr.js'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
extra:
  version:
    provider: 'mike'
